apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: optima-dapr
spec:
  type: state.redis
  metadata:
  - name: actorStateStore 
    value: "true"
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password